//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEDigitalDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter_ServiceLine_KPIs
    {
        public int ID { get; set; }
        public int FK_CostCenterServiceline { get; set; }
        public int FK_KPI { get; set; }
        public int FK_FiscalYear { get; set; }
        public System.DateTime KPIDate { get; set; }
        public Nullable<double> KPIReportingFTEs { get; set; }
        public double Target { get; set; }
        public double Value { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual CostCenter_ServiceLine CostCenter_ServiceLine { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual KPI KPI { get; set; }
    }
}
