//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEDigitalDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Digital_COEEntities : DbContext
    {
        public Digital_COEEntities()
            : base("name=Digital_COEEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<CostCenter_ServiceLine> CostCenter_ServiceLine { get; set; }
        public virtual DbSet<CostCenter_ServiceLine_KPIs> CostCenter_ServiceLine_KPIs { get; set; }
        public virtual DbSet<CostCenterKPIsTarget> CostCenterKPIsTargets { get; set; }
        public virtual DbSet<FiscalYear> FiscalYears { get; set; }
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<KPICategory> KPICategories { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
        public virtual DbSet<ServiceLine> ServiceLines { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_CostCenterServicelineDetails> vw_CostCenterServicelineDetails { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int USP_Menu_Delete(Nullable<int> menuIdentity)
        {
            var menuIdentityParameter = menuIdentity.HasValue ?
                new ObjectParameter("MenuIdentity", menuIdentity) :
                new ObjectParameter("MenuIdentity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Menu_Delete", menuIdentityParameter);
        }
    
        public virtual ObjectResult<string> USP_Menu_Insert(string menuID, string menuName, string parent_MenuID, string user_Roll, string menuFileName, string menuURL, string uSE_YN)
        {
            var menuIDParameter = menuID != null ?
                new ObjectParameter("MenuID", menuID) :
                new ObjectParameter("MenuID", typeof(string));
    
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            var parent_MenuIDParameter = parent_MenuID != null ?
                new ObjectParameter("Parent_MenuID", parent_MenuID) :
                new ObjectParameter("Parent_MenuID", typeof(string));
    
            var user_RollParameter = user_Roll != null ?
                new ObjectParameter("User_Roll", user_Roll) :
                new ObjectParameter("User_Roll", typeof(string));
    
            var menuFileNameParameter = menuFileName != null ?
                new ObjectParameter("MenuFileName", menuFileName) :
                new ObjectParameter("MenuFileName", typeof(string));
    
            var menuURLParameter = menuURL != null ?
                new ObjectParameter("MenuURL", menuURL) :
                new ObjectParameter("MenuURL", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Menu_Insert", menuIDParameter, menuNameParameter, parent_MenuIDParameter, user_RollParameter, menuFileNameParameter, menuURLParameter, uSE_YNParameter);
        }
    
        public virtual ObjectResult<USP_Menu_Select_Result> USP_Menu_Select(string menuID, string menuName)
        {
            var menuIDParameter = menuID != null ?
                new ObjectParameter("MenuID", menuID) :
                new ObjectParameter("MenuID", typeof(string));
    
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Menu_Select_Result>("USP_Menu_Select", menuIDParameter, menuNameParameter);
        }
    
        public virtual ObjectResult<string> USP_Menu_Update(Nullable<int> menuIdentity, string menuID, string menuName, string parent_MenuID, string user_Roll, string menuFileName, string menuURL, string uSE_YN)
        {
            var menuIdentityParameter = menuIdentity.HasValue ?
                new ObjectParameter("MenuIdentity", menuIdentity) :
                new ObjectParameter("MenuIdentity", typeof(int));
    
            var menuIDParameter = menuID != null ?
                new ObjectParameter("MenuID", menuID) :
                new ObjectParameter("MenuID", typeof(string));
    
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            var parent_MenuIDParameter = parent_MenuID != null ?
                new ObjectParameter("Parent_MenuID", parent_MenuID) :
                new ObjectParameter("Parent_MenuID", typeof(string));
    
            var user_RollParameter = user_Roll != null ?
                new ObjectParameter("User_Roll", user_Roll) :
                new ObjectParameter("User_Roll", typeof(string));
    
            var menuFileNameParameter = menuFileName != null ?
                new ObjectParameter("MenuFileName", menuFileName) :
                new ObjectParameter("MenuFileName", typeof(string));
    
            var menuURLParameter = menuURL != null ?
                new ObjectParameter("MenuURL", menuURL) :
                new ObjectParameter("MenuURL", typeof(string));
    
            var uSE_YNParameter = uSE_YN != null ?
                new ObjectParameter("USE_YN", uSE_YN) :
                new ObjectParameter("USE_YN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Menu_Update", menuIdentityParameter, menuIDParameter, menuNameParameter, parent_MenuIDParameter, user_RollParameter, menuFileNameParameter, menuURLParameter, uSE_YNParameter);
        }
    
        public virtual ObjectResult<USP_MenubyUserRole_Select_Result> USP_MenubyUserRole_Select(string rolename)
        {
            var rolenameParameter = rolename != null ?
                new ObjectParameter("Rolename", rolename) :
                new ObjectParameter("Rolename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_MenubyUserRole_Select_Result>("USP_MenubyUserRole_Select", rolenameParameter);
        }
    
        public virtual int USP_UserRoles_Select(string rolename)
        {
            var rolenameParameter = rolename != null ?
                new ObjectParameter("Rolename", rolename) :
                new ObjectParameter("Rolename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UserRoles_Select", rolenameParameter);
        }
    }
}
