//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEDigitalDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceLine()
        {
            this.CostCenter_ServiceLine = new HashSet<CostCenter_ServiceLine>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Fk_Lead { get; set; }
        public string ServiceLineName { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCenter_ServiceLine> CostCenter_ServiceLine { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
