//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEDigitalDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CostCenterServicelineDetails
    {
        public int ServiceLineID { get; set; }
        public string ServiceLineName { get; set; }
        public string LeadName { get; set; }
        public int CostServiceID { get; set; }
        public int CostCenterID { get; set; }
        public string CostCenterName { get; set; }
        public string CostCenterServiceLineDesc { get; set; }
        public double CapacityFTEs { get; set; }
        public int CostCenterServiceLineFTEs { get; set; }
        public int CostCenterServiceLineReportingFTEs { get; set; }
    }
}
